### ISSUE TITLE
Linked CDN version of ACE is extremely outdated

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/css_injector#11]
Oops, that's 1.2.4? How old is that? (Edit: it's 8 years old.)

https://github.com/backdrop-contrib/css_injector/blob/1.x-1.x/css_injector.admin.inc#L136

Most recent version is 1.34.1, and it seems to play just nicely with this module.

https://cdnjs.com/libraries/ace

**Comment by indigoxela** [comment]
Here's a pull request, that updates the links - for your kind review @vstemen 

https://github.com/backdrop-contrib/css_injector/pull/12

**Comment by olafgrabienski** [comment]
Tested the PR on a local site (combined with PR for #13). If I don't miss anything, with the new library version everything continues to work as expected.

**Comment by klonos** [comment]
Thank you @indigoxela and @yorkshire-pudding 🙏🏼 ...eventually, I'd like to provide a setting somewhere in the UI so that people can update the links to the CDN w/o having to wait for a new release of the module. But that's good enough for now.

**Comment by yorkshire-pudding** [comment]
@klonos - Did you mean @olafgrabienski ?

**Comment by klonos** [comment]
Yes. I meant @olafgrabienski indeed 🙂
