### ISSUE TITLE
Remove text related to CSS Injector import sandbox module on drupal.org

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/css_injector#3]
On the *CSS Injector* settings page (`admin/config/development/css-injector/settings`), there is a help text about the *CSS Injector import sandbox* module:

> If you want to import your css injector files from dev site to production, you can use CSS Injector import sandox module.
> Be aware, sandbox modules are not supported and you are using it on your own risk.

AFAIK, this sandbox module exists only on drupal.org but not for Backdrop, so I'd suggest to remove the text.

**Comment by vstemen** [comment]
OK.  Done.  Thanks.

**Comment by olafgrabienski** [comment]
Thank you! (Btw, do you get noticed about *this* comment?)

**Comment by vstemen** [comment]
Yes, I got this.  I was cc'd in the email.
