### ISSUE TITLE
Doesn't work since core V1.16.0

### ISSUE THREAD

**Issue by metatop** [backdrop-contrib/css_injector#4]
Doesn't work since core V1.16.0

To make it work you have to disable:
Aggregate and compress CSS files in Performances

![css-compress](https://user-images.githubusercontent.com/35878927/82709800-b8997380-9c81-11ea-8397-585fe78840b8.png)

**Comment by vstemen** [comment]
That's a Backdrop setting in core under Configuration -> Development.  I wonder if this should be reported as an issue for core (since css_injector has been working all this time until now and has not been changed).  I don't know if there is anything in css_injector that can be changed to affect it. Unless there is some API compatibility change to backdrop that requires updates to modules such as css_injector.

**Comment by indigoxela** [comment]
>  I wonder if this should be reported as an issue for core (since css_injector has been working all this time until now and has not been changed)

@vstemen it has been reported in core Issue queue: https://github.com/backdrop/backdrop-issues/issues/4414

**Comment by indigoxela** [comment]
@metatop "Doesn't work" is a sparse description. :wink: 

You could make life easier for module/core maintainers, if you describe a bit more in detail, what is currently broken.

Is it the inserting/editing of css code? Or is the css code not added to pages? What are the steps to reproduce?

**Comment by metatop** [comment]
> 
> 
> @metatop "Doesn't work" is a sparse description. 😉
> 
> You could make life easier for module/core maintainers, if you describe a bit more in detail, what is currently broken.
> 
> Is it the inserting/editing of css code? Or is the css code not added to pages? What are the steps to reproduce?

Sorry, my English is horrible and I tend to summarize too much.

 The css code not added to pages when "aggregate and compress CSS files" is active.

**Comment by metatop** [comment]
> 
> 
> That's a Backdrop setting in core under Configuration -> Development. I wonder if this should be reported as an issue for core (since css_injector has been working all this time until now and has not been changed). I don't know if there is anything in css_injector that can be changed to affect it. Unless there is some API compatibility change to backdrop that requires updates to modules such as css_injector.

I think the same

**Comment by indigoxela** [comment]
I tried to reproduce it, but couldn't.

My steps:

- install css_injector (latest stable)
- add a rule (body {color: red})
- enabled aggregation
- made sure, text is still red, even after flushing caches

**Comment by indigoxela** [comment]
@metatop maybe it's related to settings?

Here's a screenshot of mine, can you make sure "Preprocess CSS" is turned on in your install?
![screenshot-css-injector](https://user-images.githubusercontent.com/842066/82984267-1a473e00-9ff2-11ea-86bc-9f7299d433c6.png)

**Comment by metatop** [comment]
Preprocess CSS is active.

I've tried a new site and the bug doesn't reproduce, I don't know where the bug may be, the only thing I know is that it stopped working when I installed version 1.16 in producction site.

Keep investigating...

**Comment by jenlampton** [comment]
@metatop did you run the update script `update.php` after the update to 1.16? A cache clear was needed with that update, and wihtout it a site could experience the problems you are describing here.

I'm going to mark the core issue as "cannot reproduce" until we can have someone else confirm the bug.

**Comment by metatop** [comment]
> 
> 
> @metatop did you run the update script `update.php` after the update to 1.16? A cache clear was needed with that update, and wihtout it a site could experience the problems you are describing here.
> 
> I'm going to mark the core issue as "cannot reproduce" until we can have someone else confirm the bug.
**I run update.php and also clear  cache**

**Comment by metatop** [comment]
I've finally made it work by erasing all the rules I had and creating them again.
Sorry for the inconvenience.

**Comment by indigoxela** [comment]
> I've finally made it work

@metatop glad you sorted things out.
