### ISSUE TITLE
Applying to be a (co)maintainer of this project.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/css_injector#5]
Hello @vstemen 👋🏼  ...thank you for working on porting this module to Backdrop.

I would like to offer to (co)maintain this project. If you do not wish to be a maintainer for it any longer, I'd also be happy to be the sole maintainer.

Let me know please.

**Comment by vstemen** [comment]
Hi klonos.  Sorry about the extremely slow response.  We recently moved out to our land from the city and didn't even have internet for a number of months.  I am just now starting work on getting caught up on all my online stuff.

Yes, you are welcome to become a co-maintainer.  I just now need to look into how to add you :-).

**Comment by vstemen** [comment]
OK.  I added you to the project.

**Comment by klonos** [comment]
Thank you @vstemen and sorry for the extremely late response on my end as well.

I'll add myself to the readme file, so that people can reach out to me if they need help.

Closing this issue.

**Comment by stpaultim** [comment]
I'm going to reopen this ticket, because I don't think that @klonos has been added to the README yet. Seems to me the task is not yet complete. 

:-)

**Comment by indigoxela** [comment]
@stpaultim and @klonos this still seems true at the end of 2023. :wink:

**Comment by herbdool** [comment]
I've added @klonos as co-maintainer since this was agreed on by @vstemen some time ago.

**Comment by vstemen** [comment]
Thanks @herbdool.  I thought @klonos was already added as a maintainer.  I remember adding him sometime back, so I don't know what happened.  I hope @klonos is able to do the testing and merging of these recent issues.  I am not setup to do it right now.  I plan to setup another computer for working on it before long.  Sorry, everybody, for my absence and I appreciate your patience.
