### ISSUE TITLE
Uncaught ReferenceError: Drupal is not defined

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/css_injector#9]
That's a JS error thrown, if the Drupal compatibility layer is off.

```
$settings['backdrop_drupal_compatibility'] = FALSE;
```

Without that compat setting, syntax_highlighter.js completely breaks.

Simple solution:

```
  Backdrop.behaviors.slideUpDown = {
```

**Comment by indigoxela** [comment]
A pull request is available: https://github.com/backdrop-contrib/css_injector/pull/10

@vstemen not sure, if you're still around, but if you are - please review. :smiley:

**Comment by olafgrabienski** [comment]
Confirmed the issue, and the PR fixes it for me (after clearing the CSS and JS cache).

**Comment by argiepiano** [comment]
This is good to go. I thought the @backdrop-contrib/bug-squad needed to act, but I see that @klonos is a maintainer, so I'll let him do the merging.

**Comment by indigoxela** [comment]
@klonos it's been a while now, this PR has been available for maintainer review, but you didn't find the time to chime in, yet. Any chance, this might happen soon-ish?

**Comment by klonos** [comment]
Apologies folks. Real life, work, as well as other threads in the core queue distracted me. I'm having a look now.
